<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

class StudySchedule extends Model
{
    protected $fillable = [
        'coach_id',
        'student_id',
        'name',
        'is_active',
        'is_template',
        'schedule_type',
        'visible_time_slots',
        'start_date',
        'end_date',
        'duration_days',
        'week_number',
        'is_master_template',
        'copied_from_schedule_id',
    ];

    protected function casts(): array
    {
        return [
            'is_active' => 'boolean',
            'is_template' => 'boolean',
            'is_master_template' => 'boolean',
            'start_date' => 'date',
            'end_date' => 'date',
            'week_number' => 'integer',
            'duration_days' => 'integer',
            'visible_time_slots' => 'array',
        ];
    }

    public function coach(): BelongsTo
    {
        return $this->belongsTo(User::class, 'coach_id');
    }

    public function student(): BelongsTo
    {
        return $this->belongsTo(User::class, 'student_id');
    }

    public function items(): HasMany
    {
        return $this->hasMany(ScheduleItem::class, 'schedule_id')->orderBy('day_of_week')->orderBy('order');
    }

    public function copiedFrom(): BelongsTo
    {
        return $this->belongsTo(StudySchedule::class, 'copied_from_schedule_id');
    }

    public function copiedSchedules(): HasMany
    {
        return $this->hasMany(StudySchedule::class, 'copied_from_schedule_id');
    }

    // Scope'lar
    public function scopeTemplates($query)
    {
        return $query->where('is_template', true);
    }

    public function scopeSchedules($query)
    {
        return $query->where('is_template', false);
    }

    public function scopeMasterTemplates($query)
    {
        return $query->where('is_master_template', true);
    }

    // Helper methods
    public function getAutoGeneratedName(): string
    {
        $studentName = $this->student ? $this->student->name : 'Şablon';
        return "{$studentName} - {$this->week_number}.hafta";
    }
}
